package com.example.demo.dao;

import java.util.List;

import com.example.demo.bean.ProductType;

public interface ProductTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_type
     *
     * @mbggenerated
     */
    int insert(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_type
     *
     * @mbggenerated
     */
    int insertSelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_type
     *
     * @mbggenerated
     */
    ProductType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductType record);
    
    
    List<ProductType> findAll();
    
    
    
}