package com.erpdemo.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.erpdemo.entity.DamageListEntity;
import com.erpdemo.entity.DamageListGoodsEntity;
import com.erpdemo.vo.DamageListVO;

public interface DamageListGoodsEntityMapper extends BaseDao<DamageListGoodsEntity>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_damage_list_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_damage_list_goods
     *
     * @mbggenerated
     */
    int insert(DamageListGoodsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_damage_list_goods
     *
     * @mbggenerated
     */
    int insertSelective(DamageListGoodsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_damage_list_goods
     *
     * @mbggenerated
     */
    DamageListGoodsEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_damage_list_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DamageListGoodsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_damage_list_goods
     *
     * @mbggenerated
     */
    List<DamageListGoodsEntity> queryGoods(Map<String, Object> map);
	List<DamageListVO> queryForEcharts(Map<String,Object> params);
	List<DamageListVO> queryForEchartsAvg(Map<String,Object> params);
	
    
}