package com.erpdemo.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.erpdemo.entity.GoodsCheckEntity;

public interface GoodsCheckEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_check
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_check
     *
     * @mbggenerated
     */
    int insert(GoodsCheckEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_check
     *
     * @mbggenerated
     */
    int insertSelective(GoodsCheckEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_check
     *
     * @mbggenerated
     */
    GoodsCheckEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_check
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsCheckEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_check
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsCheckEntity record);
    
    /**
     * 查询所有
     */
    public List<GoodsCheckEntity> showAll();
    
    /**
     * 分页
     */
    public List<GoodsCheckEntity> getPage(@Param("startIndex") int startIndex,@Param("pageCount") int pageCount);
    
    /**
     * 查询总记录数
     */
    public int getTotalNumber();
    
    /**
     * 保存数据
     */
//    public int save(Map<String,String>param);
    
    /**
     * 按照id获取数据
     */
   public GoodsCheckEntity getOneById(int id); 
   
   /**
    * 删除（隐藏）数据
    * @param id
    * @return
    */
   public int setDeleteFlag(int id);
   
   /**
    * 条件查询
    * @param param
    * @return
    */
   public List<GoodsCheckEntity> search(Map<String,String>param);
    
}