package com.erpdemo.entity;

import java.util.Date;

public class CustomerReturnListEntity {
	
	
	
	
	
	
    @Override
	public String toString() {
		return "CustomerReturnListEntity [id=" + id + ", amountpaid=" + amountpaid + ", amountpayable=" + amountpayable
				+ ", customerreturndate=" + customerreturndate + ", customerreturnnumber=" + customerreturnnumber
				+ ", remarks=" + remarks + ", state=" + state + ", customerid=" + customerid + ", userid=" + userid
				+ ", addtime=" + addtime + ", delflag=" + delflag + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list.amountpaid
     *
     * @mbggenerated
     */
    private Float amountpaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list.amountpayable
     *
     * @mbggenerated
     */
    private Float amountpayable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list.customerreturndate
     *
     * @mbggenerated
     */
    private Date customerreturndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list.customerreturnnumber
     *
     * @mbggenerated
     */
    private String customerreturnnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list.customerid
     *
     * @mbggenerated
     */
    private Integer customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list.delflag
     *
     * @mbggenerated
     */
    private String delflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list.id
     *
     * @return the value of t_customer_return_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list.id
     *
     * @param id the value for t_customer_return_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list.amountpaid
     *
     * @return the value of t_customer_return_list.amountpaid
     *
     * @mbggenerated
     */
    public Float getAmountpaid() {
        return amountpaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list.amountpaid
     *
     * @param amountpaid the value for t_customer_return_list.amountpaid
     *
     * @mbggenerated
     */
    public void setAmountpaid(Float amountpaid) {
        this.amountpaid = amountpaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list.amountpayable
     *
     * @return the value of t_customer_return_list.amountpayable
     *
     * @mbggenerated
     */
    public Float getAmountpayable() {
        return amountpayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list.amountpayable
     *
     * @param amountpayable the value for t_customer_return_list.amountpayable
     *
     * @mbggenerated
     */
    public void setAmountpayable(Float amountpayable) {
        this.amountpayable = amountpayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list.customerreturndate
     *
     * @return the value of t_customer_return_list.customerreturndate
     *
     * @mbggenerated
     */
    public Date getCustomerreturndate() {
        return customerreturndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list.customerreturndate
     *
     * @param customerreturndate the value for t_customer_return_list.customerreturndate
     *
     * @mbggenerated
     */
    public void setCustomerreturndate(Date customerreturndate) {
        this.customerreturndate = customerreturndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list.customerreturnnumber
     *
     * @return the value of t_customer_return_list.customerreturnnumber
     *
     * @mbggenerated
     */
    public String getCustomerreturnnumber() {
        return customerreturnnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list.customerreturnnumber
     *
     * @param customerreturnnumber the value for t_customer_return_list.customerreturnnumber
     *
     * @mbggenerated
     */
    public void setCustomerreturnnumber(String customerreturnnumber) {
        this.customerreturnnumber = customerreturnnumber == null ? null : customerreturnnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list.remarks
     *
     * @return the value of t_customer_return_list.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list.remarks
     *
     * @param remarks the value for t_customer_return_list.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list.state
     *
     * @return the value of t_customer_return_list.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list.state
     *
     * @param state the value for t_customer_return_list.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list.customerid
     *
     * @return the value of t_customer_return_list.customerid
     *
     * @mbggenerated
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list.customerid
     *
     * @param customerid the value for t_customer_return_list.customerid
     *
     * @mbggenerated
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list.userid
     *
     * @return the value of t_customer_return_list.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list.userid
     *
     * @param userid the value for t_customer_return_list.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list.addtime
     *
     * @return the value of t_customer_return_list.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list.addtime
     *
     * @param addtime the value for t_customer_return_list.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list.delflag
     *
     * @return the value of t_customer_return_list.delflag
     *
     * @mbggenerated
     */
    public String getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list.delflag
     *
     * @param delflag the value for t_customer_return_list.delflag
     *
     * @mbggenerated
     */
    public void setDelflag(String delflag) {
        this.delflag = delflag == null ? null : delflag.trim();
    }
    
    
    	
}




