package com.erpdemo.entity;

import java.util.Date;

public class GoodsCheckListEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check_list.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check_list.goodsid
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check_list.model
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check_list.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check_list.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check_list.marketnum
     *
     * @mbggenerated
     */
    private Integer marketnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check_list.returnnum
     *
     * @mbggenerated
     */
    private Integer returnnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check_list.stocknum
     *
     * @mbggenerated
     */
    private Integer stocknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check_list.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check_list.typeid
     *
     * @mbggenerated
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check_list.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check_list.result
     *
     * @mbggenerated
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check_list.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check_list.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check_list.goodscheckid
     *
     * @mbggenerated
     */
    private Integer goodscheckid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check_list.delflag
     *
     * @mbggenerated
     */
    private Integer delflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check_list.id
     *
     * @return the value of t_goods_check_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check_list.id
     *
     * @param id the value for t_goods_check_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check_list.code
     *
     * @return the value of t_goods_check_list.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check_list.code
     *
     * @param code the value for t_goods_check_list.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check_list.goodsid
     *
     * @return the value of t_goods_check_list.goodsid
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check_list.goodsid
     *
     * @param goodsid the value for t_goods_check_list.goodsid
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check_list.model
     *
     * @return the value of t_goods_check_list.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check_list.model
     *
     * @param model the value for t_goods_check_list.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check_list.name
     *
     * @return the value of t_goods_check_list.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check_list.name
     *
     * @param name the value for t_goods_check_list.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check_list.num
     *
     * @return the value of t_goods_check_list.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check_list.num
     *
     * @param num the value for t_goods_check_list.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check_list.marketnum
     *
     * @return the value of t_goods_check_list.marketnum
     *
     * @mbggenerated
     */
    public Integer getMarketnum() {
        return marketnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check_list.marketnum
     *
     * @param marketnum the value for t_goods_check_list.marketnum
     *
     * @mbggenerated
     */
    public void setMarketnum(Integer marketnum) {
        this.marketnum = marketnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check_list.returnnum
     *
     * @return the value of t_goods_check_list.returnnum
     *
     * @mbggenerated
     */
    public Integer getReturnnum() {
        return returnnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check_list.returnnum
     *
     * @param returnnum the value for t_goods_check_list.returnnum
     *
     * @mbggenerated
     */
    public void setReturnnum(Integer returnnum) {
        this.returnnum = returnnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check_list.stocknum
     *
     * @return the value of t_goods_check_list.stocknum
     *
     * @mbggenerated
     */
    public Integer getStocknum() {
        return stocknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check_list.stocknum
     *
     * @param stocknum the value for t_goods_check_list.stocknum
     *
     * @mbggenerated
     */
    public void setStocknum(Integer stocknum) {
        this.stocknum = stocknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check_list.unit
     *
     * @return the value of t_goods_check_list.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check_list.unit
     *
     * @param unit the value for t_goods_check_list.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check_list.typeid
     *
     * @return the value of t_goods_check_list.typeid
     *
     * @mbggenerated
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check_list.typeid
     *
     * @param typeid the value for t_goods_check_list.typeid
     *
     * @mbggenerated
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check_list.userid
     *
     * @return the value of t_goods_check_list.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check_list.userid
     *
     * @param userid the value for t_goods_check_list.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check_list.result
     *
     * @return the value of t_goods_check_list.result
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check_list.result
     *
     * @param result the value for t_goods_check_list.result
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check_list.memo
     *
     * @return the value of t_goods_check_list.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check_list.memo
     *
     * @param memo the value for t_goods_check_list.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check_list.addtime
     *
     * @return the value of t_goods_check_list.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check_list.addtime
     *
     * @param addtime the value for t_goods_check_list.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check_list.goodscheckid
     *
     * @return the value of t_goods_check_list.goodscheckid
     *
     * @mbggenerated
     */
    public Integer getGoodscheckid() {
        return goodscheckid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check_list.goodscheckid
     *
     * @param goodscheckid the value for t_goods_check_list.goodscheckid
     *
     * @mbggenerated
     */
    public void setGoodscheckid(Integer goodscheckid) {
        this.goodscheckid = goodscheckid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check_list.delflag
     *
     * @return the value of t_goods_check_list.delflag
     *
     * @mbggenerated
     */
    public Integer getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check_list.delflag
     *
     * @param delflag the value for t_goods_check_list.delflag
     *
     * @mbggenerated
     */
    public void setDelflag(Integer delflag) {
        this.delflag = delflag;
    }

	public GoodsCheckListEntity(Integer id, String code, Integer goodsid, String model, String name, Integer num,
			Integer marketnum, Integer returnnum, Integer stocknum, String unit, Integer typeid, Integer userid,
			String result, String memo, Date addtime, Integer goodscheckid, Integer delflag) {
		super();
		this.id = id;
		this.code = code;
		this.goodsid = goodsid;
		this.model = model;
		this.name = name;
		this.num = num;
		this.marketnum = marketnum;
		this.returnnum = returnnum;
		this.stocknum = stocknum;
		this.unit = unit;
		this.typeid = typeid;
		this.userid = userid;
		this.result = result;
		this.memo = memo;
		this.addtime = addtime;
		this.goodscheckid = goodscheckid;
		this.delflag = delflag;
	}

	public GoodsCheckListEntity() {
		super();
	}

	@Override
	public String toString() {
		return "GoodsCheckListEntity [id=" + id + ", code=" + code + ", goodsid=" + goodsid + ", model=" + model + ", name="
				+ name + ", num=" + num + ", marketnum=" + marketnum + ", returnnum=" + returnnum + ", stocknum="
				+ stocknum + ", unit=" + unit + ", typeid=" + typeid + ", userid=" + userid + ", result=" + result
				+ ", memo=" + memo + ", addtime=" + addtime + ", goodscheckid=" + goodscheckid + ", delflag=" + delflag
				+ "]";
	}
    
    
    
    
    
    
}