package com.erpdemo.entity;

import java.util.Date;

public class OverFlowListGoodsEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list_goods.id
     *
     * @mbggenerated
     */
	//主键
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list_goods.code
     *
     * @mbggenerated
     */
    //商品编号
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list_goods.goodsid
     *
     * @mbggenerated
     */
    //关联商品表id
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list_goods.model
     *
     * @mbggenerated
     */
    //商品类型
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list_goods.name
     *
     * @mbggenerated
     */
    //商品名称
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list_goods.num
     *
     * @mbggenerated
     */
    //商品报溢数量
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list_goods.price
     *
     * @mbggenerated
     */
    //该次报溢价格
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list_goods.total
     *
     * @mbggenerated
     */
    //报溢商品总价值
    private Float total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list_goods.unit
     *
     * @mbggenerated
     */
    //单位
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list_goods.overflowlistid
     *
     * @mbggenerated
     */
    //关联报溢单id
    private Integer overflowlistid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list_goods.typeid
     *
     * @mbggenerated
     */
    //关联商品种类id
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list_goods.delflag
     *
     * @mbggenerated
     */
    //逻辑删除标识位
    private Integer delflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list_goods.addtime
     *
     * @mbggenerated
     */
    //注册时间(尚未设置)
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list_goods.userid
     *
     * @mbggenerated
     */
    //关联用户id
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list_goods.id
     *
     * @return the value of t_overflow_list_goods.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list_goods.id
     *
     * @param id the value for t_overflow_list_goods.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list_goods.code
     *
     * @return the value of t_overflow_list_goods.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list_goods.code
     *
     * @param code the value for t_overflow_list_goods.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list_goods.goodsid
     *
     * @return the value of t_overflow_list_goods.goodsid
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list_goods.goodsid
     *
     * @param goodsid the value for t_overflow_list_goods.goodsid
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list_goods.model
     *
     * @return the value of t_overflow_list_goods.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list_goods.model
     *
     * @param model the value for t_overflow_list_goods.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list_goods.name
     *
     * @return the value of t_overflow_list_goods.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list_goods.name
     *
     * @param name the value for t_overflow_list_goods.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list_goods.num
     *
     * @return the value of t_overflow_list_goods.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list_goods.num
     *
     * @param num the value for t_overflow_list_goods.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list_goods.price
     *
     * @return the value of t_overflow_list_goods.price
     *
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list_goods.price
     *
     * @param price the value for t_overflow_list_goods.price
     *
     * @mbggenerated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list_goods.total
     *
     * @return the value of t_overflow_list_goods.total
     *
     * @mbggenerated
     */
    public Float getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list_goods.total
     *
     * @param total the value for t_overflow_list_goods.total
     *
     * @mbggenerated
     */
    public void setTotal(Float total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list_goods.unit
     *
     * @return the value of t_overflow_list_goods.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list_goods.unit
     *
     * @param unit the value for t_overflow_list_goods.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list_goods.overflowlistid
     *
     * @return the value of t_overflow_list_goods.overflowlistid
     *
     * @mbggenerated
     */
    public Integer getOverflowlistid() {
        return overflowlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list_goods.overflowlistid
     *
     * @param overflowlistid the value for t_overflow_list_goods.overflowlistid
     *
     * @mbggenerated
     */
    public void setOverflowlistid(Integer overflowlistid) {
        this.overflowlistid = overflowlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list_goods.typeid
     *
     * @return the value of t_overflow_list_goods.typeid
     *
     * @mbggenerated
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list_goods.typeid
     *
     * @param typeid the value for t_overflow_list_goods.typeid
     *
     * @mbggenerated
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list_goods.delflag
     *
     * @return the value of t_overflow_list_goods.delflag
     *
     * @mbggenerated
     */
    public Integer getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list_goods.delflag
     *
     * @param delflag the value for t_overflow_list_goods.delflag
     *
     * @mbggenerated
     */
    public void setDelflag(Integer delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list_goods.addtime
     *
     * @return the value of t_overflow_list_goods.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list_goods.addtime
     *
     * @param addtime the value for t_overflow_list_goods.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list_goods.userid
     *
     * @return the value of t_overflow_list_goods.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list_goods.userid
     *
     * @param userid the value for t_overflow_list_goods.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}