package com.erpdemo.entity;

import java.util.Date;

public class OverFlowListEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list.id
     *
     * @mbggenerated
     */
	//主键
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list.overflowdate
     *
     * @mbggenerated
     */
    //添加时间（已设置为自动获取  now() ）
    private Date overflowdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list.overflownumber
     *
     * @mbggenerated
     */
    //报溢单号
    private String overflownumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list.remarks
     *
     * @mbggenerated
     */
    //备注
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list.userid
     *
     * @mbggenerated
     */
    //关联用户表id
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list.delflag
     *
     * @mbggenerated
     */
    //逻辑删除
    private Integer delflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_overflow_list.addtime
     *
     * @mbggenerated
     */
    //添加到数据库时间（已设置为自动获取  now() ）
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list.id
     *
     * @return the value of t_overflow_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list.id
     *
     * @param id the value for t_overflow_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list.overflowdate
     *
     * @return the value of t_overflow_list.overflowdate
     *
     * @mbggenerated
     */
    public Date getOverflowdate() {
        return overflowdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list.overflowdate
     *
     * @param overflowdate the value for t_overflow_list.overflowdate
     *
     * @mbggenerated
     */
    public void setOverflowdate(Date overflowdate) {
        this.overflowdate = overflowdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list.overflownumber
     *
     * @return the value of t_overflow_list.overflownumber
     *
     * @mbggenerated
     */
    public String getOverflownumber() {
        return overflownumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list.overflownumber
     *
     * @param overflownumber the value for t_overflow_list.overflownumber
     *
     * @mbggenerated
     */
    public void setOverflownumber(String overflownumber) {
        this.overflownumber = overflownumber == null ? null : overflownumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list.remarks
     *
     * @return the value of t_overflow_list.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list.remarks
     *
     * @param remarks the value for t_overflow_list.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list.userid
     *
     * @return the value of t_overflow_list.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list.userid
     *
     * @param userid the value for t_overflow_list.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list.delflag
     *
     * @return the value of t_overflow_list.delflag
     *
     * @mbggenerated
     */
    public Integer getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list.delflag
     *
     * @param delflag the value for t_overflow_list.delflag
     *
     * @mbggenerated
     */
    public void setDelflag(Integer delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_overflow_list.addtime
     *
     * @return the value of t_overflow_list.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_overflow_list.addtime
     *
     * @param addtime the value for t_overflow_list.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}