package com.erpdemo.entity;

public class PurchaseGoodsEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list_goods.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list_goods.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list_goods.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list_goods.model
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list_goods.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list_goods.num
     *
     * @mbggenerated
     */
    private Float num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list_goods.price
     *
     * @mbggenerated
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list_goods.total
     *
     * @mbggenerated
     */
    private Float total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list_goods.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list_goods.purchase_list_id
     *
     * @mbggenerated
     */
    private Integer purchaseListId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list_goods.type_id
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list_goods.id
     *
     * @return the value of t_purchase_list_goods.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list_goods.id
     *
     * @param id the value for t_purchase_list_goods.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list_goods.code
     *
     * @return the value of t_purchase_list_goods.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list_goods.code
     *
     * @param code the value for t_purchase_list_goods.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list_goods.goods_id
     *
     * @return the value of t_purchase_list_goods.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list_goods.goods_id
     *
     * @param goodsId the value for t_purchase_list_goods.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list_goods.model
     *
     * @return the value of t_purchase_list_goods.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list_goods.model
     *
     * @param model the value for t_purchase_list_goods.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list_goods.name
     *
     * @return the value of t_purchase_list_goods.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list_goods.name
     *
     * @param name the value for t_purchase_list_goods.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list_goods.num
     *
     * @return the value of t_purchase_list_goods.num
     *
     * @mbggenerated
     */
    public Float getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list_goods.num
     *
     * @param num the value for t_purchase_list_goods.num
     *
     * @mbggenerated
     */
    public void setNum(Float num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list_goods.price
     *
     * @return the value of t_purchase_list_goods.price
     *
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list_goods.price
     *
     * @param price the value for t_purchase_list_goods.price
     *
     * @mbggenerated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list_goods.total
     *
     * @return the value of t_purchase_list_goods.total
     *
     * @mbggenerated
     */
    public Float getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list_goods.total
     *
     * @param total the value for t_purchase_list_goods.total
     *
     * @mbggenerated
     */
    public void setTotal(Float total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list_goods.unit
     *
     * @return the value of t_purchase_list_goods.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list_goods.unit
     *
     * @param unit the value for t_purchase_list_goods.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list_goods.purchase_list_id
     *
     * @return the value of t_purchase_list_goods.purchase_list_id
     *
     * @mbggenerated
     */
    public Integer getPurchaseListId() {
        return purchaseListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list_goods.purchase_list_id
     *
     * @param purchaseListId the value for t_purchase_list_goods.purchase_list_id
     *
     * @mbggenerated
     */
    public void setPurchaseListId(Integer purchaseListId) {
        this.purchaseListId = purchaseListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list_goods.type_id
     *
     * @return the value of t_purchase_list_goods.type_id
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list_goods.type_id
     *
     * @param typeId the value for t_purchase_list_goods.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
}