package com.erpdemo.entity;

import java.util.Date;

public class ReturnListEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return_list.amountpaid
     *
     * @mbggenerated
     */
    private Float amountpaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return_list.amountpayable
     *
     * @mbggenerated
     */
    private Float amountpayable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return_list.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return_list.returndate
     *
     * @mbggenerated
     */
    private Date returndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return_list.returnnumber
     *
     * @mbggenerated
     */
    private String returnnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return_list.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return_list.supplierid
     *
     * @mbggenerated
     */
    private Integer supplierid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return_list.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return_list.delflag
     *
     * @mbggenerated
     */
    private Integer delflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return_list.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_list.id
     *
     * @return the value of t_return_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_list.id
     *
     * @param id the value for t_return_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_list.amountpaid
     *
     * @return the value of t_return_list.amountpaid
     *
     * @mbggenerated
     */
    public Float getAmountpaid() {
        return amountpaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_list.amountpaid
     *
     * @param amountpaid the value for t_return_list.amountpaid
     *
     * @mbggenerated
     */
    public void setAmountpaid(Float amountpaid) {
        this.amountpaid = amountpaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_list.amountpayable
     *
     * @return the value of t_return_list.amountpayable
     *
     * @mbggenerated
     */
    public Float getAmountpayable() {
        return amountpayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_list.amountpayable
     *
     * @param amountpayable the value for t_return_list.amountpayable
     *
     * @mbggenerated
     */
    public void setAmountpayable(Float amountpayable) {
        this.amountpayable = amountpayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_list.remarks
     *
     * @return the value of t_return_list.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_list.remarks
     *
     * @param remarks the value for t_return_list.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_list.returndate
     *
     * @return the value of t_return_list.returndate
     *
     * @mbggenerated
     */
    public Date getReturndate() {
        return returndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_list.returndate
     *
     * @param returndate the value for t_return_list.returndate
     *
     * @mbggenerated
     */
    public void setReturndate(Date returndate) {
        this.returndate = returndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_list.returnnumber
     *
     * @return the value of t_return_list.returnnumber
     *
     * @mbggenerated
     */
    public String getReturnnumber() {
        return returnnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_list.returnnumber
     *
     * @param returnnumber the value for t_return_list.returnnumber
     *
     * @mbggenerated
     */
    public void setReturnnumber(String returnnumber) {
        this.returnnumber = returnnumber == null ? null : returnnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_list.state
     *
     * @return the value of t_return_list.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_list.state
     *
     * @param state the value for t_return_list.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_list.supplierid
     *
     * @return the value of t_return_list.supplierid
     *
     * @mbggenerated
     */
    public Integer getSupplierid() {
        return supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_list.supplierid
     *
     * @param supplierid the value for t_return_list.supplierid
     *
     * @mbggenerated
     */
    public void setSupplierid(Integer supplierid) {
        this.supplierid = supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_list.userid
     *
     * @return the value of t_return_list.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_list.userid
     *
     * @param userid the value for t_return_list.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_list.delflag
     *
     * @return the value of t_return_list.delflag
     *
     * @mbggenerated
     */
    public Integer getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_list.delflag
     *
     * @param delflag the value for t_return_list.delflag
     *
     * @mbggenerated
     */
    public void setDelflag(Integer delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_list.addtime
     *
     * @return the value of t_return_list.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_list.addtime
     *
     * @param addtime the value for t_return_list.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}