package com.erpdemo.entity;

import java.util.Date;

public class SysDealerEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dealer.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dealer.createdatetime
     *
     * @mbggenerated
     */
    private Date createdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dealer.userid
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dealer.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dealer.linkman
     *
     * @mbggenerated
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dealer.tele
     *
     * @mbggenerated
     */
    private String tele;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dealer.addr
     *
     * @mbggenerated
     */
    private String addr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dealer.id
     *
     * @return the value of sys_dealer.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dealer.id
     *
     * @param id the value for sys_dealer.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dealer.createdatetime
     *
     * @return the value of sys_dealer.createdatetime
     *
     * @mbggenerated
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dealer.createdatetime
     *
     * @param createdatetime the value for sys_dealer.createdatetime
     *
     * @mbggenerated
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dealer.userid
     *
     * @return the value of sys_dealer.userid
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dealer.userid
     *
     * @param userid the value for sys_dealer.userid
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dealer.name
     *
     * @return the value of sys_dealer.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dealer.name
     *
     * @param name the value for sys_dealer.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dealer.linkman
     *
     * @return the value of sys_dealer.linkman
     *
     * @mbggenerated
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dealer.linkman
     *
     * @param linkman the value for sys_dealer.linkman
     *
     * @mbggenerated
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dealer.tele
     *
     * @return the value of sys_dealer.tele
     *
     * @mbggenerated
     */
    public String getTele() {
        return tele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dealer.tele
     *
     * @param tele the value for sys_dealer.tele
     *
     * @mbggenerated
     */
    public void setTele(String tele) {
        this.tele = tele == null ? null : tele.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dealer.addr
     *
     * @return the value of sys_dealer.addr
     *
     * @mbggenerated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dealer.addr
     *
     * @param addr the value for sys_dealer.addr
     *
     * @mbggenerated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }
}