package com.erpdemo.entity;

import java.util.Date;

public class CustomerReturnListGoodsEntity {
	
	
	
	
	
    @Override
	public String toString() {
		return "CustomerReturnListGoodsEntity [id=" + id + ", code=" + code + ", goodsid=" + goodsid + ", model="
				+ model + ", name=" + name + ", num=" + num + ", price=" + price + ", total=" + total + ", unit=" + unit
				+ ", customerreturnlistid=" + customerreturnlistid + ", typeid=" + typeid + ", addtime=" + addtime
				+ ", userid=" + userid + ", delflag=" + delflag + "]";
	}
    
    

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list_goods.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list_goods.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list_goods.goodsid
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list_goods.model
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list_goods.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list_goods.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list_goods.price
     *
     * @mbggenerated
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list_goods.total
     *
     * @mbggenerated
     */
    private Float total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list_goods.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list_goods.customerreturnlistid
     *
     * @mbggenerated
     */
    private Integer customerreturnlistid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list_goods.typeid
     *
     * @mbggenerated
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list_goods.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list_goods.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_return_list_goods.delflag
     *
     * @mbggenerated
     */
    private String delflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list_goods.id
     *
     * @return the value of t_customer_return_list_goods.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list_goods.id
     *
     * @param id the value for t_customer_return_list_goods.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list_goods.code
     *
     * @return the value of t_customer_return_list_goods.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list_goods.code
     *
     * @param code the value for t_customer_return_list_goods.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list_goods.goodsid
     *
     * @return the value of t_customer_return_list_goods.goodsid
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list_goods.goodsid
     *
     * @param goodsid the value for t_customer_return_list_goods.goodsid
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list_goods.model
     *
     * @return the value of t_customer_return_list_goods.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list_goods.model
     *
     * @param model the value for t_customer_return_list_goods.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list_goods.name
     *
     * @return the value of t_customer_return_list_goods.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list_goods.name
     *
     * @param name the value for t_customer_return_list_goods.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list_goods.num
     *
     * @return the value of t_customer_return_list_goods.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list_goods.num
     *
     * @param num the value for t_customer_return_list_goods.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list_goods.price
     *
     * @return the value of t_customer_return_list_goods.price
     *
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list_goods.price
     *
     * @param price the value for t_customer_return_list_goods.price
     *
     * @mbggenerated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list_goods.total
     *
     * @return the value of t_customer_return_list_goods.total
     *
     * @mbggenerated
     */
    public Float getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list_goods.total
     *
     * @param total the value for t_customer_return_list_goods.total
     *
     * @mbggenerated
     */
    public void setTotal(Float total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list_goods.unit
     *
     * @return the value of t_customer_return_list_goods.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list_goods.unit
     *
     * @param unit the value for t_customer_return_list_goods.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list_goods.customerreturnlistid
     *
     * @return the value of t_customer_return_list_goods.customerreturnlistid
     *
     * @mbggenerated
     */
    public Integer getCustomerreturnlistid() {
        return customerreturnlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list_goods.customerreturnlistid
     *
     * @param customerreturnlistid the value for t_customer_return_list_goods.customerreturnlistid
     *
     * @mbggenerated
     */
    public void setCustomerreturnlistid(Integer customerreturnlistid) {
        this.customerreturnlistid = customerreturnlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list_goods.typeid
     *
     * @return the value of t_customer_return_list_goods.typeid
     *
     * @mbggenerated
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list_goods.typeid
     *
     * @param typeid the value for t_customer_return_list_goods.typeid
     *
     * @mbggenerated
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list_goods.addtime
     *
     * @return the value of t_customer_return_list_goods.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list_goods.addtime
     *
     * @param addtime the value for t_customer_return_list_goods.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list_goods.userid
     *
     * @return the value of t_customer_return_list_goods.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list_goods.userid
     *
     * @param userid the value for t_customer_return_list_goods.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_return_list_goods.delflag
     *
     * @return the value of t_customer_return_list_goods.delflag
     *
     * @mbggenerated
     */
    public String getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_return_list_goods.delflag
     *
     * @param delflag the value for t_customer_return_list_goods.delflag
     *
     * @mbggenerated
     */
    public void setDelflag(String delflag) {
        this.delflag = delflag == null ? null : delflag.trim();
    }
}