package com.erpdemo.entity;

import java.util.Date;

public class DamageListEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_damage_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_damage_list.damagedate
     *
     * @mbggenerated
     */
    private Date damagedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_damage_list.damagenumber
     *
     * @mbggenerated
     */
    private String damagenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_damage_list.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_damage_list.delflag
     *
     * @mbggenerated
     */
    private Integer delflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_damage_list.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_damage_list.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_damage_list.id
     *
     * @return the value of t_damage_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_damage_list.id
     *
     * @param id the value for t_damage_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_damage_list.damagedate
     *
     * @return the value of t_damage_list.damagedate
     *
     * @mbggenerated
     */
    public Date getDamagedate() {
        return damagedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_damage_list.damagedate
     *
     * @param damagedate the value for t_damage_list.damagedate
     *
     * @mbggenerated
     */
    public void setDamagedate(Date damagedate) {
        this.damagedate = damagedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_damage_list.damagenumber
     *
     * @return the value of t_damage_list.damagenumber
     *
     * @mbggenerated
     */
    public String getDamagenumber() {
        return damagenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_damage_list.damagenumber
     *
     * @param damagenumber the value for t_damage_list.damagenumber
     *
     * @mbggenerated
     */
    public void setDamagenumber(String damagenumber) {
        this.damagenumber = damagenumber == null ? null : damagenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_damage_list.remarks
     *
     * @return the value of t_damage_list.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_damage_list.remarks
     *
     * @param remarks the value for t_damage_list.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_damage_list.delflag
     *
     * @return the value of t_damage_list.delflag
     *
     * @mbggenerated
     */
    public Integer getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_damage_list.delflag
     *
     * @param delflag the value for t_damage_list.delflag
     *
     * @mbggenerated
     */
    public void setDelflag(Integer delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_damage_list.addtime
     *
     * @return the value of t_damage_list.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_damage_list.addtime
     *
     * @param addtime the value for t_damage_list.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_damage_list.userid
     *
     * @return the value of t_damage_list.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_damage_list.userid
     *
     * @param userid the value for t_damage_list.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}