package com.erpdemo.entity;

import java.util.Date;

public class GoodsColorEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_color.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_color.tid
     *
     * @mbggenerated
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_color.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_color.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_color.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_color.delflag
     *
     * @mbggenerated
     */
    private Integer delflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_color.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_color.id
     *
     * @return the value of t_goods_color.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_color.id
     *
     * @param id the value for t_goods_color.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_color.tid
     *
     * @return the value of t_goods_color.tid
     *
     * @mbggenerated
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_color.tid
     *
     * @param tid the value for t_goods_color.tid
     *
     * @mbggenerated
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_color.name
     *
     * @return the value of t_goods_color.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_color.name
     *
     * @param name the value for t_goods_color.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_color.price
     *
     * @return the value of t_goods_color.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_color.price
     *
     * @param price the value for t_goods_color.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_color.userid
     *
     * @return the value of t_goods_color.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_color.userid
     *
     * @param userid the value for t_goods_color.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_color.delflag
     *
     * @return the value of t_goods_color.delflag
     *
     * @mbggenerated
     */
    public Integer getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_color.delflag
     *
     * @param delflag the value for t_goods_color.delflag
     *
     * @mbggenerated
     */
    public void setDelflag(Integer delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_color.addtime
     *
     * @return the value of t_goods_color.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_color.addtime
     *
     * @param addtime the value for t_goods_color.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}