package com.erpdemo.entity;

import java.util.Date;

public class GoodsCheckEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check.checknumber
     *
     * @mbggenerated
     */
    private String checknumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check.stocknum
     *
     * @mbggenerated
     */
    private Integer stocknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check.result
     *
     * @mbggenerated
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check.checknum
     *
     * @mbggenerated
     */
    private Integer checknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_check.delflag
     *
     * @mbggenerated
     */
    private Integer delflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check.id
     *
     * @return the value of t_goods_check.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check.id
     *
     * @param id the value for t_goods_check.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check.checknumber
     *
     * @return the value of t_goods_check.checknumber
     *
     * @mbggenerated
     */
    public String getChecknumber() {
        return checknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check.checknumber
     *
     * @param checknumber the value for t_goods_check.checknumber
     *
     * @mbggenerated
     */
    public void setChecknumber(String checknumber) {
        this.checknumber = checknumber == null ? null : checknumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check.stocknum
     *
     * @return the value of t_goods_check.stocknum
     *
     * @mbggenerated
     */
    public Integer getStocknum() {
        return stocknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check.stocknum
     *
     * @param stocknum the value for t_goods_check.stocknum
     *
     * @mbggenerated
     */
    public void setStocknum(Integer stocknum) {
        this.stocknum = stocknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check.result
     *
     * @return the value of t_goods_check.result
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check.result
     *
     * @param result the value for t_goods_check.result
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check.checknum
     *
     * @return the value of t_goods_check.checknum
     *
     * @mbggenerated
     */
    public Integer getChecknum() {
        return checknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check.checknum
     *
     * @param checknum the value for t_goods_check.checknum
     *
     * @mbggenerated
     */
    public void setChecknum(Integer checknum) {
        this.checknum = checknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check.userid
     *
     * @return the value of t_goods_check.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check.userid
     *
     * @param userid the value for t_goods_check.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check.memo
     *
     * @return the value of t_goods_check.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check.memo
     *
     * @param memo the value for t_goods_check.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check.addtime
     *
     * @return the value of t_goods_check.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check.addtime
     *
     * @param addtime the value for t_goods_check.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_check.delflag
     *
     * @return the value of t_goods_check.delflag
     *
     * @mbggenerated
     */
    public Integer getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_check.delflag
     *
     * @param delflag the value for t_goods_check.delflag
     *
     * @mbggenerated
     */
    public void setDelflag(Integer delflag) {
        this.delflag = delflag;
    }

	public GoodsCheckEntity(Integer id, String checknumber, Integer stocknum, String result, Integer checknum, Integer userid,
			String memo, Date addtime, Integer delflag) {
		super();
		this.id = id;
		this.checknumber = checknumber;
		this.stocknum = stocknum;
		this.result = result;
		this.checknum = checknum;
		this.userid = userid;
		this.memo = memo;
		this.addtime = addtime;
		this.delflag = delflag;
	}

	public GoodsCheckEntity() {
		super();
	}

	@Override
	public String toString() {
		return "GoodsCheckEntity [id=" + id + ", checknumber=" + checknumber + ", stocknum=" + stocknum + ", result=" + result
				+ ", checknum=" + checknum + ", userid=" + userid + ", memo=" + memo + ", addtime=" + addtime
				+ ", delflag=" + delflag + "]";
	}
    
    
    
    
    
}