package com.erpdemo.entity;

import java.util.Date;

public class PurchaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list.amountpaid
     *
     * @mbggenerated
     */
    private Float amountpaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list.amountpayable
     *
     * @mbggenerated
     */
    private Float amountpayable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list.purchasedate
     *
     * @mbggenerated
     */
    private Date purchasedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list.purchasenumber
     *
     * @mbggenerated
     */
    private String purchasenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list.supplier_id
     *
     * @mbggenerated
     */
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list.amount_paid
     *
     * @mbggenerated
     */
    private Float amountPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list.amount_payable
     *
     * @mbggenerated
     */
    private Float amountPayable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list.purchase_date
     *
     * @mbggenerated
     */
    private Date purchaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchase_list.purchase_number
     *
     * @mbggenerated
     */
    private String purchaseNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list.id
     *
     * @return the value of t_purchase_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list.id
     *
     * @param id the value for t_purchase_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list.amountpaid
     *
     * @return the value of t_purchase_list.amountpaid
     *
     * @mbggenerated
     */
    public Float getAmountpaid() {
        return amountpaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list.amountpaid
     *
     * @param amountpaid the value for t_purchase_list.amountpaid
     *
     * @mbggenerated
     */
    public void setAmountpaid(Float amountpaid) {
        this.amountpaid = amountpaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list.amountpayable
     *
     * @return the value of t_purchase_list.amountpayable
     *
     * @mbggenerated
     */
    public Float getAmountpayable() {
        return amountpayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list.amountpayable
     *
     * @param amountpayable the value for t_purchase_list.amountpayable
     *
     * @mbggenerated
     */
    public void setAmountpayable(Float amountpayable) {
        this.amountpayable = amountpayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list.purchasedate
     *
     * @return the value of t_purchase_list.purchasedate
     *
     * @mbggenerated
     */
    public Date getPurchasedate() {
        return purchasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list.purchasedate
     *
     * @param purchasedate the value for t_purchase_list.purchasedate
     *
     * @mbggenerated
     */
    public void setPurchasedate(Date purchasedate) {
        this.purchasedate = purchasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list.purchasenumber
     *
     * @return the value of t_purchase_list.purchasenumber
     *
     * @mbggenerated
     */
    public String getPurchasenumber() {
        return purchasenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list.purchasenumber
     *
     * @param purchasenumber the value for t_purchase_list.purchasenumber
     *
     * @mbggenerated
     */
    public void setPurchasenumber(String purchasenumber) {
        this.purchasenumber = purchasenumber == null ? null : purchasenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list.remarks
     *
     * @return the value of t_purchase_list.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list.remarks
     *
     * @param remarks the value for t_purchase_list.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list.state
     *
     * @return the value of t_purchase_list.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list.state
     *
     * @param state the value for t_purchase_list.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list.supplier_id
     *
     * @return the value of t_purchase_list.supplier_id
     *
     * @mbggenerated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list.supplier_id
     *
     * @param supplierId the value for t_purchase_list.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list.user_id
     *
     * @return the value of t_purchase_list.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list.user_id
     *
     * @param userId the value for t_purchase_list.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list.amount_paid
     *
     * @return the value of t_purchase_list.amount_paid
     *
     * @mbggenerated
     */
    public Float getAmountPaid() {
        return amountPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list.amount_paid
     *
     * @param amountPaid the value for t_purchase_list.amount_paid
     *
     * @mbggenerated
     */
    public void setAmountPaid(Float amountPaid) {
        this.amountPaid = amountPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list.amount_payable
     *
     * @return the value of t_purchase_list.amount_payable
     *
     * @mbggenerated
     */
    public Float getAmountPayable() {
        return amountPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list.amount_payable
     *
     * @param amountPayable the value for t_purchase_list.amount_payable
     *
     * @mbggenerated
     */
    public void setAmountPayable(Float amountPayable) {
        this.amountPayable = amountPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list.purchase_date
     *
     * @return the value of t_purchase_list.purchase_date
     *
     * @mbggenerated
     */
    public Date getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list.purchase_date
     *
     * @param purchaseDate the value for t_purchase_list.purchase_date
     *
     * @mbggenerated
     */
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchase_list.purchase_number
     *
     * @return the value of t_purchase_list.purchase_number
     *
     * @mbggenerated
     */
    public String getPurchaseNumber() {
        return purchaseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchase_list.purchase_number
     *
     * @param purchaseNumber the value for t_purchase_list.purchase_number
     *
     * @mbggenerated
     */
    public void setPurchaseNumber(String purchaseNumber) {
        this.purchaseNumber = purchaseNumber == null ? null : purchaseNumber.trim();
    }
}