package com.erpdemo.entity;

import java.util.Date;

public class SysProductEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.createdatetime
     *
     * @mbggenerated
     */
    private Date createdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.userid
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.pcode
     *
     * @mbggenerated
     */
    private String pcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.priceIn
     *
     * @mbggenerated
     */
    private Double pricein;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.weight
     *
     * @mbggenerated
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.onhand
     *
     * @mbggenerated
     */
    private Integer onhand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.cid
     *
     * @mbggenerated
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.priceOut
     *
     * @mbggenerated
     */
    private Double priceout;
    
    private SysUserEntity user;
    
    private SysCategoryEntity category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.id
     *
     * @return the value of sys_product.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.id
     *
     * @param id the value for sys_product.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.createdatetime
     *
     * @return the value of sys_product.createdatetime
     *
     * @mbggenerated
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.createdatetime
     *
     * @param createdatetime the value for sys_product.createdatetime
     *
     * @mbggenerated
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.userid
     *
     * @return the value of sys_product.userid
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.userid
     *
     * @param userid the value for sys_product.userid
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.name
     *
     * @return the value of sys_product.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.name
     *
     * @param name the value for sys_product.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.pcode
     *
     * @return the value of sys_product.pcode
     *
     * @mbggenerated
     */
    public String getPcode() {
        return pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.pcode
     *
     * @param pcode the value for sys_product.pcode
     *
     * @mbggenerated
     */
    public void setPcode(String pcode) {
        this.pcode = pcode == null ? null : pcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.priceIn
     *
     * @return the value of sys_product.priceIn
     *
     * @mbggenerated
     */
    public Double getPricein() {
        return pricein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.priceIn
     *
     * @param pricein the value for sys_product.priceIn
     *
     * @mbggenerated
     */
    public void setPricein(Double pricein) {
        this.pricein = pricein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.weight
     *
     * @return the value of sys_product.weight
     *
     * @mbggenerated
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.weight
     *
     * @param weight the value for sys_product.weight
     *
     * @mbggenerated
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.onhand
     *
     * @return the value of sys_product.onhand
     *
     * @mbggenerated
     */
    public Integer getOnhand() {
        return onhand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.onhand
     *
     * @param onhand the value for sys_product.onhand
     *
     * @mbggenerated
     */
    public void setOnhand(Integer onhand) {
        this.onhand = onhand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.cid
     *
     * @return the value of sys_product.cid
     *
     * @mbggenerated
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.cid
     *
     * @param cid the value for sys_product.cid
     *
     * @mbggenerated
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.priceOut
     *
     * @return the value of sys_product.priceOut
     *
     * @mbggenerated
     */
    public Double getPriceout() {
        return priceout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.priceOut
     *
     * @param priceout the value for sys_product.priceOut
     *
     * @mbggenerated
     */
    public void setPriceout(Double priceout) {
        this.priceout = priceout;
    }

	public SysUserEntity getUser() {
		return user;
	}

	public void setUser(SysUserEntity user) {
		this.user = user;
	}

	public SysCategoryEntity getCategory() {
		return category;
	}

	public void setCategory(SysCategoryEntity category) {
		this.category = category;
	}
    
    
}