package com.erpdemo.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.erpdemo.entity.Goods;

public interface GoodsMapper extends BaseDao<Goods> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_goods
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_goods
	 *
	 * @mbggenerated
	 */
	int insert(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_goods
	 *
	 * @mbggenerated
	 */
	int insertSelective(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_goods
	 *
	 * @mbggenerated
	 */
	Goods selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_goods
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_goods
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Goods record);

	List<Goods> queryAll();

	List<Goods> findForSearch(@Param("name") String name, @Param("index") int index, @Param("count") int count);

}