package com.erpdemo.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.erpdemo.entity.GoodsCheckEntity;
import com.erpdemo.entity.GoodsCheckListEntity;

public interface GoodsCheckListEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_check_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_check_list
     *
     * @mbggenerated
     */
    int insert(GoodsCheckListEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_check_list
     *
     * @mbggenerated
     */
    int insertSelective(GoodsCheckListEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_check_list
     *
     * @mbggenerated
     */
    GoodsCheckListEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_check_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsCheckListEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_check_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsCheckListEntity record);
    
    /**
     * 查询所有
     */
    public List<GoodsCheckListEntity> showAll();
    
    /**
     * 分页
     */
    public List<GoodsCheckListEntity> getPage(@Param("startIndex") int startIndex,@Param("pageCount") int pageCount);
    
    /**
     * 查询总记录数
     */
    public int getTotalNumber();
    
    /**
     * 保存数据
     */
//    public int save(Map<String,String>param);
    
    /**
     * 按照id获取数据
     */
   public GoodsCheckListEntity getOneById(int id); 
   
   /**
    * 删除（隐藏）数据
    * @param id
    * @return
    */
   public int setDeleteFlag(int id);
   
   /**
    * 条件查询
    * @param param
    * @return
    */
   public List<GoodsCheckListEntity> search(Map<String,String>param);
}