package com.erpdemo.dao;

import com.erpdemo.entity.OverFlowListGoodsEntity;

public interface OverFlowListGoodsEntityMapper extends BaseDao<OverFlowListGoodsEntity>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_overflow_list_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_overflow_list_goods
     *
     * @mbggenerated
     */
    int insert(OverFlowListGoodsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_overflow_list_goods
     *
     * @mbggenerated
     */
    int insertSelective(OverFlowListGoodsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_overflow_list_goods
     *
     * @mbggenerated
     */
    OverFlowListGoodsEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_overflow_list_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OverFlowListGoodsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_overflow_list_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OverFlowListGoodsEntity record);
    
  //逻辑删除
  	void updateList(Long [] ids);
}