package com.example.demo.bean;

import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.ptypeid
     *
     * @mbggenerated
     */
    private Integer ptypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.addtime
     *
     * @mbggenerated
     */
    private Date addtime;
    
    private ProductType productType;
    
    
    public ProductType getProductType() {
		return productType;
	}

	public void setProductType(ProductType productType) {
		this.productType = productType;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.id
     *
     * @return the value of tb_product.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.id
     *
     * @param id the value for tb_product.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.name
     *
     * @return the value of tb_product.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.name
     *
     * @param name the value for tb_product.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.price
     *
     * @return the value of tb_product.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.price
     *
     * @param price the value for tb_product.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.num
     *
     * @return the value of tb_product.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.num
     *
     * @param num the value for tb_product.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.ptypeid
     *
     * @return the value of tb_product.ptypeid
     *
     * @mbggenerated
     */
    public Integer getPtypeid() {
        return ptypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.ptypeid
     *
     * @param ptypeid the value for tb_product.ptypeid
     *
     * @mbggenerated
     */
    public void setPtypeid(Integer ptypeid) {
        this.ptypeid = ptypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.addtime
     *
     * @return the value of tb_product.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.addtime
     *
     * @param addtime the value for tb_product.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}